import { Phones } from 'types/phones.ts';
import Phone1 from 'assets/phones/image1.jpeg';
import Phone2 from 'assets/phones/image2.jpeg';
import Phone3 from 'assets/phones/image3.jpeg';
import Phone4 from 'assets/phones/image4.jpeg';
import Phone5 from 'assets/phones/image5.jpeg';
import Phone6 from 'assets/phones/image6.jpeg';
import Phone7 from 'assets/phones/image7.jpeg';

export const initialState: Phones[] = [
  {
    id: 1,
    title: 'Apple iPhone Xs 64GB Silver (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: true,
    price: 899,
    forSalePrice: 799,
    isInBasket: false,
    image: Phone1,
  },
  {
    id: 2,
    title: 'Apple iPhone 11 Pro Max 64GB Gold (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: true,
    price: 1999,
    forSalePrice: 1199,
    isInBasket: false,
    image: Phone2,
  },
  {
    id: 3,
    title: 'Apple iPhone 11 128GB Purple (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: true,
    isForSale: true,
    price: 899,
    forSalePrice: 799,
    isInBasket: false,
    image: Phone3,
  },
  {
    id: 4,
    title: 'Apple iPhone X 256GB Silver (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: true,
    price: 859,
    forSalePrice: 899,
    isInBasket: false,
    image: Phone4,
  },
  {
    id: 5,
    title: 'Apple iPhone 11 Pro Max 512GB Midnight Green (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: true,
    isForSale: true,
    price: 899,
    forSalePrice: 799,
    isInBasket: false,
    image: Phone5,
  },
  {
    id: 6,
    title: 'Apple iPhone 11 256GB Purple (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: false,
    price: 899,
    forSalePrice: null,
    isInBasket: false,
    image: Phone6,
  },
  {
    id: 7,
    title: 'Apple iPhone 11 Pro Max 512GB Midnight Green (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: false,
    price: 1299,
    forSalePrice: null,
    isInBasket: false,
    image: Phone7,
  },
  {
    id: 8,
    title: 'Apple iPhone Xs 64GB Silver (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: true,
    price: 899,
    forSalePrice: 799,
    isInBasket: false,
    image: Phone1,
  },
  {
    id: 9,
    title: 'Apple iPhone 11 Pro Max 64GB Gold (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: true,
    price: 1999,
    forSalePrice: 1199,
    isInBasket: false,
    image: Phone2,
  },
  {
    id: 10,
    title: 'Apple iPhone 11 128GB Purple (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: true,
    isForSale: true,
    price: 899,
    forSalePrice: 799,
    isInBasket: false,
    image: Phone3,
  },
  {
    id: 11,
    title: 'Apple iPhone X 256GB Silver (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: true,
    price: 859,
    forSalePrice: 899,
    isInBasket: false,
    image: Phone4,
  },
  {
    id: 12,
    title: 'Apple iPhone 11 Pro Max 512GB Midnight Green (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: true,
    isForSale: true,
    price: 899,
    forSalePrice: 799,
    isInBasket: false,
    image: Phone5,
  },
  {
    id: 13,
    title: 'Apple iPhone 11 256GB Purple (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: false,
    price: 899,
    forSalePrice: null,
    isInBasket: false,
    image: Phone6,
  },
  {
    id: 14,
    title: 'Apple iPhone 11 Pro Max 512GB Midnight Green (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: false,
    price: 1299,
    forSalePrice: null,
    isInBasket: false,
    image: Phone7,
  },
  {
    id: 15,
    title: 'Apple iPhone Xs 64GB Silver (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: true,
    price: 899,
    forSalePrice: 799,
    isInBasket: false,
    image: Phone1,
  },
  {
    id: 16,
    title: 'Apple iPhone 11 Pro Max 64GB Gold (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: true,
    price: 1999,
    forSalePrice: 1199,
    isInBasket: false,
    image: Phone2,
  },
  {
    id: 17,
    title: 'Apple iPhone 11 128GB Purple (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: true,
    isForSale: true,
    price: 899,
    forSalePrice: 799,
    isInBasket: false,
    image: Phone3,
  },
  {
    id: 18,
    title: 'Apple iPhone X 256GB Silver (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: true,
    price: 859,
    forSalePrice: 899,
    isInBasket: false,
    image: Phone4,
  },
  {
    id: 19,
    title: 'Apple iPhone 11 Pro Max 512GB Midnight Green (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: true,
    isForSale: true,
    price: 899,
    forSalePrice: 799,
    isInBasket: false,
    image: Phone5,
  },
  {
    id: 20,
    title: 'Apple iPhone 11 256GB Purple (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: false,
    price: 899,
    forSalePrice: null,
    isInBasket: false,
    image: Phone6,
  },
  {
    id: 21,
    title: 'Apple iPhone 11 Pro Max 512GB Midnight Green (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: false,
    price: 1299,
    forSalePrice: null,
    isInBasket: false,
    image: Phone7,
  },
  {
    id: 22,
    title: 'Apple iPhone Xs 64GB Silver (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: true,
    price: 899,
    forSalePrice: 799,
    isInBasket: false,
    image: Phone1,
  },
  {
    id: 23,
    title: 'Apple iPhone 11 Pro Max 64GB Gold (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: true,
    price: 1999,
    forSalePrice: 1199,
    isInBasket: false,
    image: Phone2,
  },
  {
    id: 24,
    title: 'Apple iPhone 11 128GB Purple (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: true,
    isForSale: true,
    price: 899,
    forSalePrice: 799,
    isInBasket: false,
    image: Phone3,
  },
  {
    id: 25,
    title: 'Apple iPhone X 256GB Silver (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: true,
    price: 859,
    forSalePrice: 899,
    isInBasket: false,
    image: Phone4,
  },
  {
    id: 26,
    title: 'Apple iPhone 11 Pro Max 512GB Midnight Green (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: true,
    isForSale: true,
    price: 899,
    forSalePrice: 799,
    isInBasket: false,
    image: Phone5,
  },
  {
    id: 27,
    title: 'Apple iPhone 11 256GB Purple (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: false,
    price: 899,
    forSalePrice: null,
    isInBasket: false,
    image: Phone6,
  },
  {
    id: 28,
    title: 'Apple iPhone 11 Pro Max 512GB Midnight Green (iMT9G2FS/A)',
    category: 'phones',
    isFavourite: false,
    isForSale: false,
    price: 1299,
    forSalePrice: null,
    isInBasket: false,
    image: Phone7,
  },
];
